# Generated by Django 5.2 on 2025-08-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0006_mensajecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='imagen_pago',
            field=models.ImageField(blank=True, null=True, upload_to='pago_images/'),
        ),
    ]
