# Generated by Django 5.1.1 on 2025-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0007_cuentacorriente_imagen_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('cleaned_sender_pn', models.CharField(blank=True, max_length=50, null=True)),
                ('esperando_opcion', models.BooleanField(default=False)),
                ('paso', models.CharField(blank=True, max_length=50, null=True)),
                ('ultimo_texto', models.TextField(blank=True, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado del Chat',
                'verbose_name_plural': 'Estados del Chat',
                'db_table': 'CarritoApp_chat_estado',
            },
        ),
    ]
